d3.select('body')
  .append('p').html('<h1>Have a good time!<h1>')
  .append('div').html('<br><h2>Learn html element.style from here!</h2>')
  .style('background', '#115545')
  .style('width', '600px')
  .style('height', '220px')
  .style('margin-left','10%')
  .style('padding-left','5%')
  .style('padding-top','5%')
  .style('color','#12ff56')
  .append('a').attr('href','https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style')
  .html('<br><b>HTML Element.style（英文）</b>')
  .style('color','yellow')
  .append('a').attr('href','https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/style')
  .html('<br><b>HTML Element.style(中文) </b>')
  .style('color','#ff2366')
